apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-container
          image: ghcr.io/cbhavya09/demo-cicd-docker/my-docker-image:latest
          ports:
            - containerPort: 3000
