name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          install_kubectl: true

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --push -t ghcr.io/cbhavya09/demo-cicd-docker/my-docker-image:latest .
        env:
          DOCKER_CLI_AGGREGATE: 1
          DOCKER_BUILDKIT: 1

      - name: Deploy to Kubernetes
        run: kubectl apply -f kubernetes/deployment.yaml

